---
title: "Big Papas Summary 2018"
author: "Christian Ashcraft"
date: "May 23, 2019"
output: html_document
keep_md: true 
---

```{r warning=FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(readr)
library(lubridate)
```


```{r warning=FALSE}
#Importing and Tidying Square Report

squ <- read.csv("data/BP_2018_Sales.csv") %>% 
  filter(Event.Type == "Payment", Gross.Sales != "$0.00")
  

squ <- squ[c(-3,-6,-7,-8,-9,-15,-16,-17,-18,-19,-20,-21,-22,-23,-24)]
squ$Gross.Sales <- parse_number(squ$Gross.Sales)
squ$Tax <- parse_number(squ$Tax)
squ$Date = parse_date(squ$Date, "%m/%d/%y")
squ$Category <- gsub("Fry", "Fries", squ$Category)
squ$Category <- gsub("None", "Toppings", squ$Category)
squ$temp <- squ$Date
squ <- squ %>% 
  separate(temp, into = c("year", "month", "day"), sep = "-")

sort <- squ %>%
  mutate(weekday = weekdays(Date)) %>% 
  group_by(Date, weekday, Transaction.ID) %>% 
  summarise(Gross.Sales = sum(Gross.Sales), Tax = sum(Tax), items = n()) %>% 
  group_by(Date, weekday) %>% 
  summarise(gross = sum(Gross.Sales), tax = sum(Tax), sales = n()) %>% 
  filter(gross > 10) %>% 
    mutate(location = case_when(
      weekday == "Wednesday" & gross < 250 ~ "Rigby Market",
      weekday == "Friday" & gross < 450 ~ "Rex Market",
      Date >= "2018-08-15" & Date <= "2018-08-18" ~ "Madison Fair",
      Date >= "2018-08-05" & Date <= "2018-08-11" ~ "Mudlake Fair",
      Date == "2018-08-23" ~ "St. Anthony Days",
      Date == "2018-09-22" ~ "Experience Rexburg",
      Date == "2018-07-04" ~ "Rex July 4th",
      Date == "2018-07-21" ~ "Sugar City Days",
      Date == "2018-07-09" ~ "Rex Summerfest",
      Date == "2018-07-14" ~ "Rig Car Show",
      TRUE ~ "Rigby Lake Car Show")) %>% 
  mutate(semester = case_when(
    Date >= "2018-04-23" & Date <= "2018-07-23" ~ "Spring",
    Date >= "2018-07-24" & Date <= "2018-09-16" ~ "Summer",
    Date >= "2018-09-17" & Date <= "2018-12-20" ~ "Fall",
  )) %>% 
  mutate(hours = case_when(
    location == "Rex Market" ~ "5",
    location == "Rigby Market" ~ "5",
    location == "Experience Rexburg" ~ "6",
    TRUE ~ "10"
  )) %>% 
  mutate(employees = case_when(
    location == "Rigby Market" ~ "2",
    location == "Sugar City Days" ~ "2",
    location == "Rex Market" & gross < 250 ~ "2",
    gross > 700 ~ "4",
    TRUE ~ "3"
  )) %>% 
  mutate(estpayroll8 = round(as.numeric(employees)*as.numeric(hours)*8.8, 2),
         estprodcost = round(.25*gross, 2),
         estnet = round(gross - estpayroll8 - estprodcost - tax, 2),
         avesale = round(gross/sales, 2))

```



```{r warning=FALSE}
sort %>%
  group_by(location) %>% 
  summarise(Profit = sum(estnet)) %>% 
  ggplot() +
  geom_col(aes(location, Profit, fill = location)) + 
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1), legend.position = "none") +
  scale_y_continuous(labels = scales::dollar) +
  labs(x = "Location", y = "Estimated Profit")

```




```{r warning=FALSE}

sort %>% 
  ggplot() +
  geom_point(aes(Date, sales, color = location, shape = employees), size = 2.5) + 
  geom_line(aes(Date, sales, color = location)) +
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  labs(x = "Date", y = "Number of Sales", color = "Location")


sort %>% 
  ggplot() +
  geom_point(aes(Date, estnet, color = location, shape = employees), size = 2.5) + 
  geom_line(aes(Date, estnet, color = location)) +
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  scale_y_continuous(labels = scales::dollar) +
  labs(x = "Date", y = "Estimated Profit", color = "Location")


sort %>% 
  ggplot() +
  geom_point(aes(location, estnet, color = location), size = 2) + 
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1), legend.position = "none") +
  scale_y_continuous(labels = scales::dollar) +
  labs(x = "Location", y = "Estimated Profit")


```



Date == "2018-08-15" | Date == "2018-08-16" | Date == "2018-08-17" | Date == "2018-08-18" ~ Madison Fair,
```{r warning=FALSE}
#Importing and Tidying Beehive Bank Statements

bee <- read.csv("data/Beehive_Statements_2018.csv", row.names = NULL, stringsAsFactors = FALSE, na.strings = "")
bee <- bee %>% 
  rename(account = row.names, suffix = Account, sequence.number = Suffix, transaction.date = Sequence.Number, transaction.amount = Transaction.Date, description = Transaction.Amount, extended.description = Description, electronic.transaction.date = Extended.Description, electronic.transaction.time = Electronic.Transaction.Date, balance = Electronic.Transaction.Time, none = Balance)

bee <- bee[c(-1,-2,-7,-11)]

bee$transaction.date = parse_date(bee$transaction.date)
bee$electronic.transaction.date = as.Date(bee$transaction.date, "%m-%d-%y")
bee$transaction.amount = parse_number(bee$transaction.amount)
bee$electronic.transaction.time = parse_time(bee$electronic.transaction.time)

bee <- bee %>% 
  separate(electronic.transaction.date, into = c("year", "month", "day"), sep = "-")


binc <- subset(bee, transaction.amount > 0)

bexp <- subset(bee, transaction.amount < 0)
```


```{r warning=FALSE}
#Importing Daily Sales Summaries
ds <- read.csv("data/Daily_Sales_Matrix.csv")
ds <- as.data.frame(ds)
ds <- t(ds)


```



```{r warning=FALSE}
# Horizontal Bar Charts

bee %>%
  group_by(month,description) %>% 
  summarize(amount = sum(transaction.amount)) %>% 
  ggplot() +
  geom_col(aes(reorder(description, desc(amount)), amount, fill = description)) +
  facet_wrap(~month, scales = "free", nrow = 2) +
  theme_bw() +
  theme(legend.position = "none", axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) 
  
```



```{r warning=FALSE}

squ %>%
  group_by(Date, month) %>%
  summarise(sum(Gross.Sales)) %>% 
  ggplot(aes(Date, `sum(Gross.Sales)`)) +
        geom_point(size = 3) +
  facet_wrap(~month, scales = "free_x", nrow = 4)
  
t1 <- table(squ$Item)
t1 %>%
  barplot()


squ %>% 
  filter(Category != "Drinks") %>% 
  filter(Category != "Sauce") %>% 
  filter(Item != "Xtra Sauce") %>% 
  ggplot(aes(Item)) +
  geom_bar() +
  facet_wrap(~month, scales = "free_x")




```










