---
title: "Research Question Report"
author: "Christian Ashcraft"
date: "May 1, 2019"
output: 
  html_document: 
    keep_md: yes
---


#Task 3: Research Question Report

This task seeks to give us practice in finding a good, practical research question.  

###Question 1

>*Is there a correlation between local government structure and government employee turnover rate?*

**Feedback**  

* Positive
    + This is an interesting question.
    + Turnover data would likely be easily accessible and easy to measure.
    + Sounds orginal. 

* Negative
    + This would require defining categories of government structure which could take a lot of time.
    + Some data might not be available.
    + Might not be very useful in the end because I probably won't be able to narrow it down to causation, maybe not even correlation.
    + If the intent is to measure productivity with turnover, there are other metrics that may be more accurate.
    + Not sure how far back you'd have to go to find enough data on turnovers.

###Question 2

>*Is there a correlation between local government employee headcount and their turnover rates?*

**Feedback**

* Positive
    + Sounds easy to measure and access the data.
    + Could take a relatively short time.

* Negative
    + Too broad. Knowing the answer wouldn't really make a difference.
    + What is the purpose?

###Question 3

>*What trends are there in the use of employee benefits at BYU-Idaho? Does it across departments, ages, employee types, year, etc.?*

**Feedback**

* Positive
    + Very useful and interesting information would come from this question.
    + The data involved should be easy to manipulate.
    + The data retrieved for this question would likely be very accurate.

* Negative
    + Could get too complicated
    + Might be too broad

###Question 4

>*Do turnover trends exist across BYU-Idaho departments and employee types?*

**Feedback**

* Positive
    + Would be interesting to know
    + BYU-Idaho would be interested to know.
    
* Negative
    + Wouldn't compare with industry norms very well
    + We might already know the answers without doing an analysis
    + Some of the data may not be available


###Question 5

>*What is the cost of a BYU-Idaho new hire? What is the composition of this cost?*

**Feedback**

* Positive
    + Very useful information for BYU-Idaho
    + Could expose areas that could be improved, which would lead to action

* Negative
    + Some of the data might not exist
    + Could be a lengthy project
    + It would be very difficult to conduct a comprehensive study
